FindROOT: Addressed a conflict with travis-ci build system
The errors are seen when compiling with ROOT v5.34.30.
The errors are:

Error: cannot open file "bits/predefs.h"  /usr/include/features.h:325:
Error: cannot open file "gnu/stubs.h"  /usr/include/features.h:390:
Error: Symbol __BEGIN_DECLS#define __need_size_t#define __need_NULL#include is not defined in current scope  /usr/include/stdio.h:45:
Error: Symbol stddef is not defined in current scope  /usr/include/stdio.h:45:
Error: Failed to evaluate stddef.h